<?php
    require_once "includes/core/dao/dao_langue.php";
    require_once "includes/core/dao/dao_editeur.php";
    require_once "includes/core/dao/dao_format.php";
    require_once "includes/core/dao/dao_genre.php";
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="public/styles/style.css" type="text/css"/>
    <title>Ajout / Edition livre</title>
</head>
<body>
    <header>
         <nav>
            <?php require_once "includes/partials/navbar.phtml"; ?>
        </nav>
    </header>
    <main class='flex aliCen'>
        <!--Formulaire d'ajout d'un nouveau livre-->
        <div class="form_livre flex aliCen">
            <form class="form_content flex" action="" method="post" enctype ="multipart/form-data">
                <!--Couverture-->
                <div class="champs">
                    <label for="">Couverture : </label>
                    <input type="file" name="chCouverture" id="champCouverture" value="<?= $unLivre->getCouverture() ?>"/>
                </div>
                <!--Titre-->
                <div class="champs">
                    <label for="">Titre : </label>
                    <input type="text" name="chTitre" id="champTitre" value="<?= $unLivre->getTitre() ?>"/>
                </div>
                <!--Auteur-->
                <!--Edition-->
                <div class="champs">
                    <label for="">Édition : </label>
                    <input list="editeurs" name="chEdition" id="champEdition" value="<?= $unLivre->getEditeur()->getNom() ?>"/>
                    <datalist id="editeurs">
                        <?php
                            foreach($lesEditeurs as $editeur){
                                print('<option value="'.$editeur->getNom().'">');
                            }
                        ?>
                    </datalist>
                    <a href="?page=editeur&action=add">ajouter</a>
                </div>
                <!--Genre-->
                <div class="champs">
                    <label for="">Genre : </label>
                    <input list="genres" name="chGenre" id="champGenre" pattern="<?= $patternGenres ?>" value="<?= $unLivre->getGenre()->getLibelle() ?>"/>
                    <datalist id="genres">
                        <?php
                            foreach($lesGenres as $genre){
                                print('<option value="'.$genre->getLibelle().'">');
                            }
                        ?>
                    </datalist>
                    <a href="?page=genre&action=add">ajouter</a>
                </div>
                <!--Format-->
                <div class="champs">
                    <label for="">Format : </label>
                    <input list="formats" name="chFormat" id="champFormat" pattern = "<?= $patternFormats ?>" value="<?= $unLivre->getFormat()->getLibelle() ?>"/>
                    <datalist id="formats">
                        <?php
                            foreach($listeFormats as $format){
                                print('<option value="'.$format->getLibelle().'">');
                            }
                        ?>
                    </datalist>
                </div>
                <!--Nb Pages-->
                <div class="champs">
                    <label for="">Nombre de pages : </label>
                    <input type="text" name="chNbPages" id="champNbPages" value="<?= $unLivre->getNbPages() ?>"/>
                </div>
                <!--Date Parution-->
                <div class="champs">
                    <label for="">Date de parution : </label>
                    <input type="date" name="chDateParution" id="champDateParution" value="<?= $unLivre->getDateParution()->format('Y-m-d') ?>"/>
                </div>
                <!--Prix-->
                 <div class="champs">
                    <label for="">Prix : </label>
                    <input type="text" name="chPrix" id="champPrix" value="<?= $unLivre->getPrix() ?>"/> &euro;
                </div>
                <!--ISBN-->
                 <div class="champs">
                    <label for="">ISBN : </label>
                    <input type="text" name="chIsbn" id="champIsbn" value="<?= $unLivre->getNumIsbn() ?>"/> 
                </div>
                <!--Langue-->
                <div class="champs">
                    <label for="">Langue : </label>
                    <select name="chLangue" id="champLangue" value="<?= $unLivre->getLangue()->getLibelle() ?>">
                        <option value="0">--Sélectionner--</option>
                            <?php
                                foreach($lesLangues as $langue){
                                    print('<option value="'.$langue->getId().'">'.$langue->getLibelle().'</option>');
                                }
                            ?>
                    </select>
                </div>
                <!--Resume-->
                <div class="champs flex align">
                    <label for="">Résumé : </label>
                    <textarea name="chResume" id="champResume" value="<?= $unLivre->getResume() ?>"></textarea>
                </div>
                <!--Avis-->
                <div class="champs flex aliCen">
                    <label for="">Avis : </label>
                    <textarea name="chAvis" id="champAvis" value="<?= $unLivre->getAvis() ?>"></textarea>
                </div>
            
                <input type="submit" value="Submit"/>
            </form>
        </div>
    </main>
    <footer>
        <?php require_once "includes/partials/footer.phtml"; ?>
    </footer>
</body>
</html>

    