<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="public/styles/style.css" type="text/css"/>
    <title>Ajouter un livre</title>
</head>
<body>
    <main>
        <nav>
            <?php require_once "includes/partials/navbar.phtml"; ?>
        </nav>
        
        <!--Formulaire d'ajout d'un nouveau livre-->
        <form class="form_livre" action="" method="post" enctype ="multipart/form-data">
            <!--Couverture-->
            <div class="champs">
                <label for="">Couverture : </label>
                <input type="file" name="chCouverture" id="champCouverture" value="<?= $unLivre->getCouverture() ?>"/>
            </div>
            <!--Titre-->
            <div class="champs">
                <label for="">Titre : </label>
                <input type="text" name="chTitre" id="champTitre" value="<?= $unLivre->getTitre() ?>"/>
            </div>
            <!--Auteur-->
            <div class="champs">
                <label for="">Auteur : </label>
                <input type="text" name="chAuteur" id="champAuteur" value="<?= $unLivre->getAuteur() ?>"/>
            </div>
            <!--Edition-->
            <div class="champs">
                <label for="">Edition : </label>
                <input type="text" name="chEdition" id="champEdition" value="<?= $unLivre->getEditeur() ?>"/>
            </div>
            <!--Genre-->
            <div class="champs">
                <label for="">Genre : </label>
                <select name="chGenre" id="champGenre">
                    <option value="0">--Selectionner--</option>
                        <?php
                            foreach($genres as $genre){
                                print('<option value="'.$genre->getId().'">"'.$genre->getLibelle().'"</option>');
                            }
                        ?>
                </select>
            </div>
            <!--Format-->
            <div class="champs">
                <label for="">Format : </label>
                <input type="text" name="chFormat" id="champFormat" value="<?= $unLivre->getFormat() ?>"/>
            </div>
            <!--Nb Pages-->
            <div class="champs">
                <label for="">Nombre de pages : </label>
                <input type="text" name="chNbPages" id="champNbPages" value="<?= $unLivre->getNbPages() ?>"/>
            </div>
            <!--Date Parution-->
            <div class="champs">
                <label for="">Date de parution : </label>
                <input type="date" name="chDateParution" id="champDateParution" value="<?= $unLivre->getDateParution() ?>"/>
            </div>
            <!--Prix-->
             <div class="champs">
                <label for="">Prix : </label>
                <input type="text" name="chPrix" id="champPrix" value="<?= $unLivre->getPrix() ?>"/> &euro;
            </div>
            <!--Langue-->
            <div class="champs">
                <label for="">Langue : </label>
                <select name="chLangue" id="champLangue">
                    <option value="0">--Selectionner--</option>
                        <?php
                            foreach($langues as $langue){
                                print('<option value="'.$langue->getId().'">"'.$langue->getLibelle().'"</option>');
                            }
                        ?>
                </select>
            </div>
            <!--Resume-->
            <div class="champs">
                <label for="">Resume : </label>
                <input type="text" name="chResume" id="champResume" value="<?= $unLivre->getResume() ?>"/>
            </div>
            <!--Avis-->
            <div class="champs">
                <label for="">Avis : </label>
                <input type="text" name="chAvis" id="champAvis" value=""/>
            </div>
        
            <input type="submit" value="Submit"/>
        </form>
    </main>
</body>
</html>

    