

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="public/styles/style.css" type="text/css"/>
    <title>Ajouter auteur(s)</title>
</head>
<body>
    <main>
        <nav>
            <?php require_once "includes/partials/navbar.phtml"; ?>
        </nav>
        
        <form action="">
            <input type="text" name=""/>
            <input type="submit" value="Submit"/>
        </form>
    </main>
</body>
</html>