<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="public/styles/style.css" type="text/css"/>
    <title>Liste des livres</title>
</head>
<body>
     <nav>
        <?php require_once "includes/partials/navbar.phtml"; ?>
    </nav>
    <main>
        <header>
            <h1 class="listLivres">Liste des livres enregistrés</h1>
        </header>
        <a class='ajoutLivre' href="index.php?page=livre&action=add">Ajouter un livre</a>
        <table class="bookTable">
            <thead>
                <th class="th">Couverture</th>
                <th class="th">Titre</th>
                <th class="th">Editeur</th>
                <th class="th">Genre</th>
                <th class="th">Format</th>
                <th class="th">Nb Pages</th>
                <th class="th">Date</th>
                <th class="th">Prix</th>
                <th class="th">Langue</th>
                <th colspan="2">Actions</th>
            </thead>
            <tbody>
                <?php
                    foreach($livres as $livre){
                        $script= " ";
                        $script.= '<tr>';
                        $script.= '<td class="td"><a href=" ?page=livre&action=view&id='.$livre->getId().'"><img class ="couverture" src="'.$livre->getCouverture().'" alt="'.$livre->getTitre().'"</a></td>';
                        $script.= '<td class="td">'.$livre->getTitre().'</td>';
                        $script.= '<td class="td">'.$livre->getEditeur()->getNom().'</td>';
                        $script.= '<td class="td">'.$livre->getGenre()->getLibelle().'</td>';
                        $script.= '<td class="td">'.$livre->getFormat()->getLibelle().'</td>';
                        $script.= '<td class="td">'.$livre->getNbPages().'</td>';
                        $script.= '<td class="td">'.$livre->getDateParution()->format('d/m/Y').'</td>';
                        $script.= '<td class="td">'.$livre->getPrix().('</td>');
                        $script.= '<td class="td">'.$livre->getLangue()->getLibelle().'</td>';
                        $script .= '<td class="td"><a href="index.php?page=livre&action=edit&id='.$livre->getId().'">Modifier</a></td>';
                        $script .= '<td class="td"><a href="index.php?page=livre&action=delete&id='.$livre->getId().'">Supprimer</a></td>';
                        $script.= '</tr>';
                        
                        print($script);
                    }
                ?>
            </tbody>
        </table>
    </main>
    <footer>
        <?php require_once "includes/partials/footer.phtml"; ?>
    </footer>
</body>
</html>