<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="public/styles/style.css" type="text/css"/>
    <title>Document</title>
</head>
<body>
    <main>
        <nav>
            <div class="navbar">
                <?php require_once "includes/partials/navbar.phtml"; ?>
            </div>
        </nav>
        <header>
            <h1>Titre de ma page d'accueil</h1>
        </header>
        <!--<p>-->
        <!--    Mon paragraphe-->
        <!--</p>-->
        <footer>
            <?php require_once "includes/partials/footer.phtml"; ?>
        </footer>
    </main>
</body>
</html>